# .github/workflows/proxy-checker.yml
name: Proxy Checker

on:
  schedule:
    # Run every 30 minutes
    - cron: '30 */1 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'proxy_checker.py'
      - 'list.txt'
      - '.github/workflows/proxy-checker.yml'

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 170  # GitHub Actions has 6 hour limit, but we want shorter cycles

    permissions:
      contents: write  # Required to commit changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp # Removed asyncio-throttle as it's not used in proxy_checker.py

    - name: Check if required files exist
      run: |
        if [ ! -f "list.txt" ]; then
          echo "Error: list.txt not found!"
          exit 1
        fi
        if [ ! -f "proxy_checker.py" ]; then
          echo "Error: proxy_checker.py not found!"
          exit 1
        fi
        echo "Required files found"

    - name: Run proxy checker
      run: |
        python proxy_checker.py
      timeout-minutes: 160

    - name: Check if proxies.txt was created/updated
      run: |
        if [ -f "proxies.txt" ]; then
          echo "proxies.txt exists"
          wc -l proxies.txt
          echo "Sample proxies (first 10 lines):"
          head -10 proxies.txt || true # "|| true" to prevent failure if file has <10 lines
        else
          echo "No proxies.txt file created by the script."
          echo "Creating an empty proxies.txt for the commit step."
          touch proxies.txt # Create empty file if script fails to create one
        fi

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        git add proxies.txt
        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to proxies.txt to commit."
        else
          git commit -m "Update working proxies - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          # Add retry logic for push, as network hiccups can occur
          for i in 1 2 3; do
            git push && break  # Break if push succeeds
            echo "Push failed. Retrying in 15 seconds (attempt $i of 3)..."
            sleep 15
          done
          if ! git diff --quiet HEAD; then # Check if push ultimately failed
             echo "Push failed after multiple retries."
             # Optionally, you could exit 1 here if a failed push should fail the workflow
          else
             echo "Changes committed and pushed successfully."
          fi
        fi
      # No need to explicitly pass GITHUB_TOKEN here for git push if using actions/checkout@v4 with default token
      # However, if you had a PAT in secrets.GITHUB_TOKEN for cross-repo, it would be needed.
      # For same-repo commits, the default GITHUB_TOKEN provided by Actions has write permissions.

    - name: Upload proxies as artifact
      uses: actions/upload-artifact@v4 # Updated to v4
      if: always() # Ensure artifact is uploaded even if previous steps fail (e.g., push)
      with:
        name: working-proxies
        path: proxies.txt
        retention-days: 7
